app/home/forms/__init__.py
from .create_field_form import CreateFieldForm
from .create_task_form import CreateTaskForm


__all__ = ["CreateFieldForm", "CreateTaskForm"]

app/home/forms/create_field_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, FloatField, IntegerField, SelectField
from wtforms.validators import DataRequired


class CreateFieldForm(FlaskForm):
    type = SelectField("Type de terrain", choices=[
        ("culture", "Culture"),
        ("creeding", "Elevage"),
        ("others", "Autres"),
    ])
    name = StringField("Nom du terrain", validators=[DataRequired()])
    superficie = IntegerField("Superficie du terrain")
    lat = FloatField("Latitude", validators=[DataRequired()])
    long = FloatField("Longitude", validators=[DataRequired()])
    submit = SubmitField("Valider")

app/home/forms/create_task_form.py
from flask_wtf import FlaskForm
from wtforms import SelectField, DateField, TextAreaField, BooleanField
from wtforms.validators import DataRequired


class CreateTaskForm(FlaskForm):
    date = DateField("Date", validators=[DataRequired()])
    field_id = SelectField("Nom du terrain", validators=[DataRequired()])
    comment = TextAreaField("Description", validators=[DataRequired()])
    is_done = BooleanField("Tâche terminée")

    def __init__(self, current_user, *args, **kwargs):
        super(CreateTaskForm, self).__init__(*args, **kwargs)
        self.field_id.choices = [
            (field.id, field.name) for field in current_user.exploitation.field_list
        ]

app/home/__init__.py
from .routes import HOME_BP

__all__ = ["HOME_BP"]

app/home/routes.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from app.models import Field, Task

from .forms import CreateFieldForm, CreateTaskForm
from app.extensions import sql_db

HOME_BP = Blueprint(
    "home", 
    __name__, 
    template_folder="templates/",     
    static_folder="static/",
    static_url_path="/static/home/",
)


@HOME_BP.route("/", methods=["GET", "POST"])
@HOME_BP.route("/home", methods=["GET", "POST"])
@login_required
def home():
    exploitation = current_user.exploitation
    field_list = exploitation.field_list

    return render_template(
        "home.html",
        field_list=field_list,
        exploitation=exploitation,
    )


@HOME_BP.route("/terrain/creation/", methods=["GET", "POST"])
@HOME_BP.route("/terrain/maj/<field_id>/", methods=["GET", "POST"])
@login_required
def create_update_field(field_id=None):
    current_field = None if not field_id else Field.query.get(field_id)
    form = (
        CreateFieldForm(
            lat=request.args.get("latitude", type=float),
            long=request.args.get("longitude", type=float)
        )
        if current_field is None
        else CreateFieldForm(**current_field.get_default_form_values())
    )

    if form.validate_on_submit():
        new_field = Field(
            exploitation_id=current_user.exploitation_id,
            type=form.type.data,
            superficie=form.superficie.data,
            name=form.name.data,
            lat=form.lat.data,
            long=form.long.data,
        )
        if current_field:
            new_field.id = current_field.id

        field_upsert = sql_db.session.merge(new_field)
        sql_db.session.add(field_upsert)
        sql_db.session.commit()
        flash("Terrain mis à jour" if current_field else "Terrain ajouté", "success")
        return redirect(url_for("home.home"))

    return render_template("create_update_field.html", form=form, current_field=current_field)


@HOME_BP.route("/terrain/delete/<field_id>/", methods=["GET", "POST"])
@login_required
def delete_field(field_id):
    field = Field.query.get(field_id)
    sql_db.session.delete(field)
    sql_db.session.commit()
    flash(f"Terrain '{field.name}' supprimé", "success")
    return redirect(url_for("home.home"))


@HOME_BP.route("/terrain/task/", methods=["GET", "POST"])
@HOME_BP.route("/terrain/task/<field_id>/", methods=["GET", "POST"])
def show_tasks(field_id=None):
    field_list = Field.query.filter_by(
        exploitation_id=current_user.exploitation_id
    )
    field_id_list = [field.id for field in field_list]
    tasks_list = Task.query.filter(
        Task.field_id.in_(field_id_list)).order_by("date")

    form = CreateTaskForm(current_user=current_user)
    if form.validate_on_submit():
        task = Task(
            date=form.date.data,
            field_id=form.field_id.data,
            editor_id=current_user.id,
            comment=form.comment.data,
        )
        task_upsert = sql_db.session.merge(task)
        sql_db.session.add(task_upsert)
        sql_db.session.commit()

        form = CreateTaskForm(current_user=current_user)
        return redirect(url_for("home.show_tasks", tasks_list=tasks_list, form=form))

    return render_template("tasks.html", tasks_list=tasks_list, form=form)

app/home/templates/create_update_field.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}


{% block main_container %}
<div class="form-content">
    <form class="form form-horizontal" method="post" role="form" id="myform">
        {{ form.hidden_tag() }}
        {{ wtf.form_errors(form, hiddens=" only") }}

        {{ wtf.form_field(form.type) }}
        {{ wtf.form_field(form.name) }}
        {{ wtf.form_field(form.superficie) }}
        {{ wtf.form_field(form.lat) }}
        {{ wtf.form_field(form.long) }}
    </form>
</div>
<div class="button-div">
    <button type="submit" form="myform" class="btn btn-success">
        Valider
    </button>
    {% if current_field %}
    <button type="button" class="btn btn-danger" onclick=ConfirmDelete()>
        Supprimer
    </button>
    {% endif %}
</div>

<script>
    function ConfirmDelete() {
        var result = confirm("Supprimer ce terrain ?");
        if (result) {
            var delete_url = "{{ url_for('home.delete_field', field_id=current_field.id) }}";
            window.location.href = delete_url
        }
    }


</script>
{% endblock %}

app/home/templates/home.html
{% extends "base.html" %}
{% set need_map = true %}

{% block main_container %}
<div id="map" class="w-100 h-75"></div>

<script>
    // Création de la map
    var map = L.map('map').setView(["{{ exploitation.lat }}", "{{ exploitation.long }}"], 13);

    L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 19,
        attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
    }).addTo(map);

    // Ajouts et modification des marqueurs
    var iconField = L.icon({
        iconUrl: 'https://cdn-icons-png.flaticon.com/128/2190/2190158.png',
        iconSize: [30, 30],
    });
    var iconExp = L.icon({
        iconUrl: 'https://cdn-icons-png.flaticon.com/128/6610/6610122.png',
        iconSize: [30, 30],
    });


    {% for field in field_list %}
    var update_url = "{{ url_for('home.create_update_field', field_id=field.id) }}";
    var detail_url = "{{ url_for('home.show_tasks', field_id=field.id) }}";

    var html_content = "{{ field.name }} <br>"
    var html_content = html_content + "<a href=" + update_url + "> Modifier </a> <br>"
    var html_content = html_content + "<a href=" + detail_url + "> Historique & Tâches </a> <br>"

    L.marker([{{ field.lat }}, {{ field.long }}], { icon: iconField }).addTo(map).bindPopup(html_content)
    {% endfor %}

    L.marker(["{{ exploitation.lat }}", "{{ exploitation.long }}"], { icon: iconExp }).addTo(map).bindPopup('{{ exploitation.name }}')

    // Permet le clique sur la carte (efface le marqueur précédent)
    var marker = null;
    map.on('click', function (e) {
        if (marker !== null) {
            map.removeLayer(marker);
        }

        var coord = e.latlng;
        var lat = coord.lat;
        var lng = coord.lng;
        var href_str = "{{ url_for('home.create_update_field') }}?latitude=" + lat + "&longitude=" + lng;

        marker = L.marker(coord).addTo(map).bindPopup("Ajouter un <a href=" + href_str + ">nouveau terrain</a>").openPopup();
    });

</script>

{% endblock %}

app/home/templates/tasks.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('home.static', filename='css/tasks.css' ) }}">
{% endblock %}


{% block main_container %}
<div class="form-content">
    <form class="form form-horizontal" method="post" role="form" id="myform">
        {{ form.hidden_tag() }}
        {{ wtf.form_errors(form, hiddens=" only") }}

        {{ wtf.form_field(form.date) }}
        {{ wtf.form_field(form.field_id) }}
        {{ wtf.form_field(form.comment) }}
        {{ wtf.form_field(form.is_done)}}
    </form>
    <button type="submit" form="myform" class="btn btn-primary btn-lg btn-block" style="width: 100%;">
        Nouvelle tâche
    </button>
</div>
{% set onclick_url = url_for('home.show_tasks') %}

<br>
<br>
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Date</th>
            <th scope="col">Terrain</th>
            <th scope="col">Editeur</th>
            <th scope="col">Commentaire</th>
            <th scope="col">Terminée</th>
        </tr>
    </thead>
    <tbody>
        {% for task in tasks_list %}
        <tr>
            <th scope="row">{{ task.date }}</th>
            <td>{{ task.field.name }}</td>
            <td>{{ task.editor.name }} {{ task.editor.surname }}</td>
            <td>{{ task.comment }}</td>
            <td>
                {% if task.is_done %}
                <button type="button" class="btn btn-success">Fait</button>
                {% else %}
                <button type="button" class="btn btn-warning">En attente</button>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}