app/authentification/forms/__init__.py
from .login_form import LoginForm
from .register_form import RegistrationForm

__all__ = ["LoginForm", "RegistrationForm"]

app/authentification/forms/login_form.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    name = StringField("Nom d'utilisateur", validators=[DataRequired()])
    password = PasswordField("Mot de passe", validators=[DataRequired()])
    remember_me = BooleanField("Se souvenir de moi")
    submit = SubmitField("Je me connecte")

app/authentification/forms/register_form.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField, SelectField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError

from app.models import User, Exploitation


class RegistrationForm(FlaskForm):
    email = StringField("Adresse email", validators=[DataRequired(), Email()])
    name = StringField("Prénom", validators=[DataRequired()])
    surname = StringField("Nom", validators=[DataRequired()])
    password = PasswordField("Mot de passe", validators=[DataRequired()])
    password2 = PasswordField(
        "Vérification du mot de passe", validators=[DataRequired(), EqualTo("password")]
    )

    exploitation_name = StringField(
        "Nom de l'exploitation", validators=[DataRequired()]
    )
    exploitation_type = SelectField(
        "Type d'exploitation",
        choices=[
            ("scea", "Société civile d'exploitation agricole (SCEA)"),
            ("gaec", "Groupement agricole d'exploitation en commun (GAEC)"),
            ("earl", "Exploitation agricole à responsabilité limitée (EARL)"),
            ("sep" , "Société de fait / Société en participation (SEP)")
        ],
        validators=[DataRequired()],
    )
    submit = SubmitField("Créer mon compte")

    def validate_name(self, name):
        user = User.query.filter_by(name=name.data).first()
        if user is not None:
            raise ValidationError("Ce pseudo est déjà utilisé.")

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError("Cette adresse email est déjà utilisée.")

    def validate_exploitation_name(self, exploitation_name):
        exploitation = Exploitation.query.filter_by(name=exploitation_name.data).first()
        if exploitation is not None:
            raise ValidationError("Cette exploitation existe déjà.")

app/authentification/__init__.py
from .routes import AUTHENTIFICATION_BP

__all__ = ["AUTHENTIFICATION_BP"]

app/authentification/routes.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user
from werkzeug.urls import url_parse

from app.extensions import sql_db
from app.models import User, Exploitation

from .forms import LoginForm, RegistrationForm

AUTHENTIFICATION_BP = Blueprint(
    "authentification", 
    __name__, 
    template_folder="templates/",
    static_folder="static/",
    static_url_path="/static/authentification/",
)


@AUTHENTIFICATION_BP.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("home.home"))

    login_form = LoginForm()
    if login_form.validate_on_submit():
        user = User.query.filter_by(name=login_form.name.data).first()
        if user is None or not user.check_password(login_form.password.data):
            flash("Utilisateur et/ou mot de passe incorrect(s)", "danger")
            return redirect(url_for("authentification.login"))

        login_user(user, remember=login_form.remember_me.data)

        next_page = request.args.get("next")
        if not next_page or url_parse(next_page).netloc != "":
            next_page = url_for("home.home")

        return redirect(next_page)

    return render_template("login.html", title="Sign In", form=login_form)


@AUTHENTIFICATION_BP.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("home.home"))

    lat, long = (
        request.args.get("latitude", type=float),
        request.args.get("longitude", type=float),
    )

    form = RegistrationForm()
    if request.method == "POST":
        exploitation = Exploitation(
            type=form.exploitation_type.data,
            name=form.exploitation_name.data,
            lat=lat,
            long=long,
        )
        sql_db.session.add(exploitation)
        sql_db.session.commit()
        flash("Exploitation créée", "success")

        user = User(
            email=form.email.data,
            name=form.name.data,
            surname=form.surname.data,
            exploitation_id=exploitation.id,
            type="admin",
        )
        user.set_password(form.password.data)
        sql_db.session.add(user)
        sql_db.session.commit()
        flash("Utilisateur créé", "success")

        return redirect(url_for("authentification.login"))

    return render_template("register.html", title="Register", form=form)


@AUTHENTIFICATION_BP.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("authentification.login"))

app/authentification/templates/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}


{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('authentification.static', filename='css/login.css' ) }}">
{% endblock %}


{% block main_container %}
<div class="form-content">
    <form class="form form-horizontal" method="post" role="form" id="myform">
        {{ form.hidden_tag() }}
        {{ wtf.form_errors(form, hiddens=" only") }}
        {{ wtf.form_field(form.name, style="text-align: center;") }}
        {{ wtf.form_field(form.password, style="text-align: center;") }}
    </form>
</div>
<button type="submit" form="myform" class="btn btn-primary btn-lg btn-block">
    Connexion
</button>
<br>
{% set onclick_url = url_for('authentification.register') %}
<button type="button" class="btn btn-secondary btn-lg btn-block" onclick="window.location.href='{{ onclick_url }}'">
    Créer un compte
</button>
{% endblock %}

app/authentification/templates/register.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% set need_map = true %}


{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('authentification.static', filename='css/register.css' ) }}">
{% endblock %}


{% block main_container %}
<div class="form-content">
    <form class="form form-horizontal" method="post" role="form" name="myform" id="myform"
        onsubmit="return FormIsValid()">
        {{ form.hidden_tag() }}
        {{ wtf.form_errors(form, hiddens="only") }}

        {{ wtf.form_field(form.email, style="text-align: center;") }}
        {{ wtf.form_field(form.name, style="text-align: center;") }}
        {{ wtf.form_field(form.surname, style="text-align: center;") }}
        {{ wtf.form_field(form.password, style="text-align: center;") }}
        {{ wtf.form_field(form.password2, style="text-align: center;") }}
        {{ wtf.form_field(form.exploitation_name, style="text-align: center;") }}
        {{ wtf.form_field(form.exploitation_type, style="text-align: center;") }}
    </form>
    <div class="localisation-content">
        <p> Emplacement de l'exploitation :</p>
        <div class="map-content">
            <div id="map" class="w-100 h-100"></div>
        </div>
    </div>
</div>
<br>
<button id="submit-btn" type="submit" form="myform" class="btn btn-primary btn-lg btn-block" disabled>
    Inscription
</button>


<script>
    var map = L.map('map').setView([48.112030, -1.680548], 13);
    L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 19,
        attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
    }).addTo(map);


    var marker = null;
    map.on('click', function (e) {
        if (marker !== null) {
            map.removeLayer(marker);
        }

        var coord = e.latlng;
        var lat = coord.lat;
        var lng = coord.lng;
        var href_str = "{{ url_for('authentification.register') }}?latitude=" + lat + "&longitude=" + lng;

        document.myform.action = href_str;
        document.getElementById("submit-btn").disabled = false;
        marker = L.marker(coord).addTo(map);
    });
</script>
{% endblock %}